### ISSUE TITLE
Errors during import

### ISSUE THREAD

**Issue by dustingrady** [roger-/pyrtlsdr#114]
I am getting the following error when I attempt to import after installing via pip.

```
user@BenchPC:~/Documents$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rtlsdr import RtlSdr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.6/site-packages/rtlsdr/__init__.py", line 56, in <module>
    from .librtlsdr import librtlsdr
  File "/home/user/.local/lib/python3.6/site-packages/rtlsdr/librtlsdr.py", line 61, in <module>
    f = librtlsdr.rtlsdr_get_device_count
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python3: undefined symbol: rtlsdr_get_device_count

```

**Comment by dustingrady** [comment]
Disregard. It appears my driver was corrupt. Updating the RTL driver solved the import issue.
