### ISSUE TITLE
OSError: Error code -5 when requesting 524288 bytes

### ISSUE THREAD

**Issue by hshahbodaghkhan** [roger-/pyrtlsdr#115]
Hi.
Thanks for your amazing work.
I perfectly initialize and setup rtl-sdr and its dependencies.
when I run the test.py file as I mention below it did ok till I got the following error:

Configuring SDR...
  sample rate: 2.400000 MHz
  center frequency 100.000000 MHz
  gain: 8 dB
Reading samples...
  signal mean: (-0.0009202246572450086-0.0009407193052995261j)
Testing callback...
  in callback
  signal mean: (-0.0009266273648124065-0.0009216607785685398j)
  in callback
  signal mean: (-0.0009033502316935545-0.0009075389188871822j)

the error:

Traceback (most recent call last):
  File "C:\Users\Hossein\Downloads\pyrtlsdr-master\pyrtlsdr-master\test.py", line 62, in <module>
    main()
  File "C:\Users\Hossein\Downloads\pyrtlsdr-master\pyrtlsdr-master\test.py", line 44, in main
    sdr.read_samples_async(test_callback, 256*1024)
  File "C:\Users\Hossein\Downloads\pyrtlsdr-master\pyrtlsdr-master\rtlsdr\rtlsdr.py", line 648, in read_samples_async
    self.read_bytes_async(self._samples_converter_callback, num_bytes, context)
  File "C:\Users\Hossein\Downloads\pyrtlsdr-master\pyrtlsdr-master\rtlsdr\rtlsdr.py", line 593, in read_bytes_async
    % (result, num_bytes))
OSError: Error code -5 when requesting 524288 bytes 

How can I solve it?

**Comment by nocarryr** [comment]
The error code you're getting, found [here](https://github.com/libusb/libusb/blob/6816bb40a3bf3e80eb7f86f4dd368f8be76667c5/libusb/libusb.h#L1029-L1084) is `LIBUSB_ERROR_NOT_FOUND`, which isn't incredibly descriptive.

It indicates some pointer to a data structure or device being destroyed in the C world, but we somehow still have a reference to it in python.

One possibility is the `test_callback` function is being called after the async reads have been cancelled.

The callback in [test.py](https://github.com/roger-/pyrtlsdr/blob/502f31b7f3a92a744476e8778abd6ebd3021acfd/test.py#L24-L27)
```python
@limit_calls(2)
def test_callback(samples, rtlsdr_obj):
    print('  in callback')
    print('  signal mean:', sum(samples)/len(samples))
```
Uses the `@limit_calls` decorator to [cancel async reads](https://github.com/roger-/pyrtlsdr/blob/502f31b7f3a92a744476e8778abd6ebd3021acfd/rtlsdr/helpers.py#L88) after 2 calls:
```python
def wrapper(buffer, rtlsdr_obj):
    f._num_calls += 1

    if f._num_calls <= max_calls:
        return f(buffer, rtlsdr_obj)

    rtlsdr_obj.cancel_read_async()
```

From my own experience, the mechanisms in place to avoid these issues have worked perfectly, but I wonder if there's something specific to your setup.

Can you provide your platform info (Python version, OS, etc) and your device type?

Also, try modifying the value in the `@limit_calls` decorator to see if that affects the number of `in callback...` messages you see
